
---- DROP COMMANDS ----
DROP TABLE employee;

DROP TABLE job_request;

DROP TABLE candidate;

--------------------------------------------------------------------------------------------------------------------------
CREATE TABLE role(
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR2(30)
);

INSERT INTO role(role)
VALUES
('SDE');

SELECT * FROM role;

CREATE TABLE skill(
    skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill VARCHAR(30)
);

INSERT INTO skill(skill)
VALUES
('C++');

INSERT INTO skill(skill)
VALUES
('Java');

INSERT INTO skill(skill)
VALUES
('Python');

SELECT * FROM skill;

CREATE TABLE employee(
    emp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50),
    password VARCHAR2(50) DEFAULT 'user@123',
    role_id NUMBER(10),
    phone_no NUMBER(20),
    email VARCHAR2(50),
    status VARCHAR2(50),
    skill1_id NUMBER(10),
    skill2_id NUMBER(10),
    skill3_id NUMBER(10),
    CONSTRAINT employee_role_id_fk FOREIGN KEY(role_id) REFERENCES role(role_id),
    CONSTRAINT employee_skill_id_fk1 FOREIGN KEY(skill1_id) REFERENCES skill(skill_id),
    CONSTRAINT employee_skill_id_fk2 FOREIGN KEY(skill2_id) REFERENCES skill(skill_id),
    CONSTRAINT employee_skill_id_fk3 FOREIGN KEY(skill3_id) REFERENCES skill(skill_id)
);

ALTER TABLE employee ADD CONSTRAINT employee_status_ck CHECK(status IN ('active','inactive'));

ALTER TABLE employee MODIFY status DEFAULT 'active'; 
ALTER TABLE employee MODIFY name NOT NULL; 
ALTER TABLE employee MODIFY email UNIQUE NOT NULL;

DESC employee;

INSERT INTO employee(name, role_id, phone_no, email, status, skill1_id)
VALUES 
('gold', 1, 9444678398, 'gold@golddigger.com', 'active', 1);

INSERT INTO employee(name, role_id, phone_no, email, skill1_id)
VALUES 
('win', 1, 9444678398, 'win@golddigger.com', 1);

SELECT * FROM employee;

--------------------------------------------------------------------------------------------

CREATE TABLE job_request(
    request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR2(2000),
    role_id NUMBER(10),
    no_of_vacancies NUMBER(5) DEFAULT 1,
    skill1_id NUMBER(10),
    skill2_id NUMBER(10),
    skill3_id NUMBER(10),
    tl_id NUMBER(10),
    filled NUMBER(10),
    pending NUMBER(10),
    created_date DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT job_request_role_id_fk FOREIGN KEY(role_id) REFERENCES role(role_id),
    CONSTRAINT job_request_tl_id_fk FOREIGN KEY(tl_id) REFERENCES employee(emp_id),
    CONSTRAINT job_request_skill_id_fk1 FOREIGN KEY(skill1_id) REFERENCES skill(skill_id),
    CONSTRAINT job_request_skill_id_fk2 FOREIGN KEY(skill2_id) REFERENCES skill(skill_id),
    CONSTRAINT job_request_skill_id_fk3 FOREIGN KEY(skill3_id) REFERENCES skill(skill_id),
    CONSTRAINT job_request_vacancies_ck CHECK(filled + pending = no_of_vacancies)
);

INSERT INTO job_request(description, role_id, no_of_vacancies, skill1_id, tl_id, filled, pending)
VALUES
('passionate and experienced', 1, 5, 1, 2, 3, 2);

-- Removes not null for created_date
ALTER TABLE job_request MODIFY created_date DATE DEFAULT SYSDATE;

ALTER TABLE job_request ADD job_req_lvl NUMBER DEFAULT 0;

SELECT * FROM job_request;

DESC job_request;
-------------------------------------------------------------------------------------------------------

CREATE TABLE candidate(
    candidate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(50) UNIQUE,
    phone_no NUMBER(20),
    role_id NUMBER(20),
    skill1_id NUMBER(10),
    skill2_id NUMBER(10),
    skill3_id NUMBER(10),
    selected_for_interview VARCHAR(1), -- SELECTED FOR TECHNICAL INTERVIEW? (y/n)
    assessment_status VARCHAR(1), -- SELECTED IN INTERVIEW CONDUCTED BY TECHNICAL PANEL? (y/n)
    confirmation_status VARCHAR(1), -- FINAL CONFIRMATION OF EMPLOYMENT (y/n)?
    request_id NUMBER(10), --FK
    interview_meet_link VARCHAR2(50),
    CONSTRAINT candidate_role_id_fk FOREIGN KEY(role_id) REFERENCES role(role_id),
    CONSTRAINT candidate_skill_id_fk1 FOREIGN KEY(skill1_id) REFERENCES skill(skill_id),
    CONSTRAINT candidate_skill_id_fk2 FOREIGN KEY(skill2_id) REFERENCES skill(skill_id),
    CONSTRAINT candidate_skill_id_fk3 FOREIGN KEY(skill3_id) REFERENCES skill(skill_id),
    CONSTRAINT candidate_selected_for_interview_ck CHECK(selected_for_interview IN ('y','n')),
    CONSTRAINT candidate_assessment_status_ck CHECK(assessment_status IN ('y','n')),
    CONSTRAINT candidate_confirmation_status_ck CHECK(confirmation_status IN ('y','n')),
    CONSTRAINT candiate_request_id_fk FOREIGN KEY(request_id) REFERENCES job_request(request_id)
);

DESC candidate;
---------------------------------------------------------
-- Employee view --
CREATE VIEW employee_view AS
SELECT emp_id, name, role_id, phone_no, email, skill1_id, skill2_id, skill3_id, status
FROM employee;

DROP VIEW employee_view;